services:
  server:
    build: .
    container_name: bia
    ports:
      - 3001:8080
    depends_on:
      - redis
    environment:
      DB_USER: postgres
      DB_PWD: l93Xp4KhciaomhgrdyEn
      DB_HOST: bia.co3qaww06tcz.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      ## NAO PRECISA NA IMERSÃO DAQUI PRA BAIXO ## 
      # DB_SECRET_NAME: 
      # DB_REGION: 
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY:
      # DEBUG_SECRET: 
      # IS_LOCAL: true 
      # CACHE_ENDPOINT: redis
      # CACHE_PORT: 6379
      # CACHE_TTL: 15
      # CACHE_TLS: false
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/api/versao"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 5s     
  redis:
    image: valkey/valkey:8.1-alpine
    container_name: redis
    ports:
      - 6379:6379
